#!/bin/bash
set -xeuo pipefail

aws s3api create-bucket --acl private --bucket "eks-cluster-playground-1" --region us-east-1

#aws dynamodb create-table --table-name "eks-cluster-playground-locks" --region us-east-1 --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST